// Mocks generated by Mockito 5.0.3 from annotations
// in routing_path/test/pattern_route_handler_test.dart.
// Do not manually edit this file.

import 'package:mockito/mockito.dart' as _i1;
import 'package:routing_path/src/pattern_route_handler.dart' as _i2;
import 'package:routing_path/src/route_arguments.dart' as _i3;

// ignore_for_file: comment_references
// ignore_for_file: unnecessary_parenthesis

class _FakeRegExp extends _i1.Fake implements RegExp {}

/// A class which mocks [PatternRouteHandler].
///
/// See the documentation for Mockito's code generation for more information.
class MockPatternRouteHandler extends _i1.Mock
    implements _i2.PatternRouteHandler {
  MockPatternRouteHandler() {
    _i1.throwOnMissingStub(this);
  }

  @override
  RegExp get pattern => (super.noSuchMethod(Invocation.getter(#pattern),
      returnValue: _FakeRegExp()) as RegExp);
  @override
  bool canOpen(String? path) => (super
          .noSuchMethod(Invocation.method(#canOpen, [path]), returnValue: false)
      as bool);
  @override
  _i3.RouteArguments? replaceMatches(
          String? path, _i3.RouteArguments? arguments) =>
      (super.noSuchMethod(Invocation.method(#replaceMatches, [path, arguments]))
          as _i3.RouteArguments?);
}
