name: routing_path
description: A lightweight path routing system
version: 0.0.1+2
homepage: https://github.com/williamhjcho/routing_path

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^4.1.0
  matcher: ^0.12.0

flutter:
